ServiceInnovationLab/serviceinnovationlab.github.io

_posts/2018-10-12-Exploring the Notice of Sale process.md
Added descriptions & alt text for pictures to Exploring the Notice of Sale process report
=> Added descriptions & alt text for pictures to Exploring the Notice of Sale process report

serve
So the dev site serves as `http://127.0.0.1:4000/`
=> Removed sub-dir from dev serve command

_plugins/utility.rb
Auto corrected by following Lint Ruby Parentheses
Click [here](https://awesomecode.io/repos/ServiceInnovationLab/serviceinnovationlab.github.io/ruby_config_groups/835) to configure it on awesomecode.io
=> Auto corrected by following Lint Ruby Parentheses

pages/contact.md
Changed from markdown to html so that the text will display.
=> Markdown to html

_includes/card_tools.html, _products_projects/api-for service-innovation.md, _products_projects/component-library.md, _products_projects/msd-family-services-directory-api.md, _products_projects/open-fisca-aotearoa.md, _products_projects/rapuTure.md, _sass/_components/card.scss, pages/tools.md
Added external link url & text to be dynamic on the Tools cards.
=> Added external link url & text to be dynamic on the Tools cards.

_includes/header.html, _layouts/home.html, _sass/_components/blog-index.scss, _sass/_components/buttons.scss, _sass/_components/header.scss, _sass/_components/hero.scss, _sass/_components/layout.scss
Fixed position of Beta word, Increase size for title & button,& added media queries.
=> Fixed position of Beta word, Increase size for title & button,& added media queries.

_about/index.md, _sass/_components/hero.scss, pages/home.html
Fixed home text position & removed line from About page
=> Fixed home text position & removed line from About page

_includes/javascript.html, _layouts/home.html
move js so its not on every page
=> move js so its not on every page

README.md
=> Add waffle badge to README

_plugins/author.rb, _plugins/author_data.rb, _plugins/embeds.rb, _plugins/liquify.rb, _plugins/markdown.rb, _plugins/matching_posts.rb, _plugins/related_posts.rb, _plugins/team.rb, _plugins/update_author_data.rb, _plugins/utility.rb, check_images.rb, config_blog.rb, spec/_plugins/author_data_spec.rb, spec/_plugins/embeds_spec.rb, spec/_plugins/team_spec.rb, spec/_plugins/utlity_spec.rb, spec/spec_helper.rb, tests/test.rb
Auto corrected by following Lint Ruby MagicComment
Click [here](https://awesomecode.io/repos/ServiceInnovationLab/serviceinnovationlab.github.io/ruby_config_groups/838) to configure it on awesomecode.io
=> Auto corrected by following Lint Ruby MagicComment

spec/_plugins/author_data_spec.rb, spec/_plugins/embeds_spec.rb, spec/_plugins/team_spec.rb, spec/_plugins/utlity_spec.rb
Auto corrected by following Lint Ruby RSpec/DescribedClass
Click [here](https://awesomecode.io/repos/ServiceInnovationLab/serviceinnovationlab.github.io/ruby_lint_configs/35654) to configure it on awesomecode.io
=> Auto corrected by following Lint Ruby RSpec/DescribedClass

assets/js/lib/jquery.ajaxchimp.js
Auto corrected by following Lint Javascript dot-notation
Click [here](https://awesomecode.io/repos/ServiceInnovationLab/serviceinnovationlab.github.io/javascript_lint_configs/50068) to configure it on awesomecode.io
=> Auto corrected by following Lint Javascript dot-notation

spec/_plugins/author_data_spec.rb, spec/_plugins/embeds_spec.rb, spec/_plugins/team_spec.rb, spec/_plugins/utlity_spec.rb
Auto corrected by following Lint Ruby RSpec/HookArgument
Click [here](https://awesomecode.io/repos/ServiceInnovationLab/serviceinnovationlab.github.io/ruby_lint_configs/35640) to configure it on awesomecode.io
=> Auto corrected by following Lint Ruby RSpec/HookArgument

WORKFLOW.md, _about/index.md, _plugins/README.md, _posts/2018-06-01-aotearoa-new-zealand-government-innovation-assets-risks-matti-schneider.md, _posts/2018-08-01-Exploring-Optimistic-Futures-Workshop.md, _posts/2018-10-12-Exploring the Notice of Sale process.md, _posts/2018-11-30-Rates-Rebate.md
Linting & Markdown edits.
Just tidying up stuff.
=> Linting & Markdown edits.

package-lock.json
Upgrade jquery to >=3.4.0 to fix vulnerability.
=> Upgrade jquery to >=3.4.0 to fix vulnerability.

_config.yml, pages/devPeerReviewWorkflow.md, pages/expertise.md
Added Dev Peer Review Workflow doc in markdown.
=> Added Dev Peer Review Workflow doc.

pages/tools.md
=> Removed unused line.

_authors/deshan-gamage.md
i created a team profile with my details
=> Create a team profile?

README.md
=> Fixed title.

README.md, _about/index.md
Changed year from 2019 to 2020.
Thanks @MerryODS for spotting that.
=> Changed year from 2019 to 2020.

_services_projects/legislation-as-code.md
=> Added summary for ACC report.

_services_projects/legislation-as-code.md
Just a couple of notes on the executive summary - sorry I didn't get to this on #252 when it was up, I was getting a coffee!
=> Add links and spellcheck

_layouts/project-page.html
Added code to allow multiple reports to appear on the page.
=> To allow multiple reports to appear.

_posts/2019-06-12-Becoming-An-Adult.md
Spelling error in filepath & made image clickable.
=> Spelling error in filepath & made image clickable.

_layouts/default.html, _layouts/home.html
There's already a title tag in the included head.html
=> Removed duplicate title

_products_projects/api-for-service-innovation.md, _products_projects/component-library.md, _products_projects/msd-family-services-directory-api.md, _products_projects/open-fisca-aotearoa.md, _products_projects/rapuTure.md, _services_projects/20-year-emtech-landscape.md, _services_projects/becoming-an-adult.md, _services_projects/consent_based_sharing.md, _services_projects/digital-nations.md, _services_projects/entering-tertiary-life-event.md, _services_projects/legislation-as-code.md, _services_projects/notice-of-sale.md, _services_projects/optimistic-futures.md, _services_projects/rates-rebate.md, _services_projects/renting-a-property.md, _services_projects/smartStart.md, _services_projects/victim-of-crime-life-event.md
Removed unused front matter data tags.
=> Removed unused front matter data tags.

_posts/2019-07-30-Rates-Rebate-Beta-Research-Report.md, _services_projects/rates-rebate.md
Changed author & display report on project card.
=> Changed author & display report on project card.

_authors/deshan-gamage.md
updating my profile details for the Team page.
=> Updating profile details

_authors/brenda-wallace.md, _authors/glen-thurston.md, _authors/karyn-brice.md, _authors/rob-holmes.md, _authors/ross-patel.md, _authors/tiopira-piripi.md
=> Updated members to alumni.

_authors/hamish-fraser.md, _authors/hazel-bradshaw.md, _authors/tim-kong.md
=> Shifted members to alumni.

_sass/_libs/wds/js/vendor/respond.js
Auto corrected by following Lint Javascript unicorn/prefer-includes
Click [here](https://awesomecode.io//repos/ServiceInnovationLab/serviceinnovationlab.github.io/lint_configs/javascript/65939) to configure it on awesomecode.io
=> Auto corrected by following Lint Javascript unicorn/prefer-includes

package-lock.json
Fix security updates/dependencies.
=> Fix security updates/dependencies.

_plugins/related_posts.rb
Auto corrected by following Lint Ruby Lint/BooleanSymbol
Click [here](https://awesomecode.io/repos/ServiceInnovationLab/serviceinnovationlab.github.io/lint_configs/ruby/6528) to configure it on awesomecode.io
=> Auto corrected by following Lint Ruby Lint/BooleanSymbol

_includes/card_tools.html, _products_projects/api-for-service-innovation.md, _products_projects/component-library.md, _products_projects/msd-family-services-directory-api.md, _products_projects/open-fisca-aotearoa.md, _products_projects/rapuTure.md
Fixed external_url & clickable card's redirect_to.
=> Fixed external_url & clickable card's redirect_to.

_includes/header.html
Changed href so url doesn't contain the trailing /
=> Changed href so url doesn't contain the trailing /

.circleci/config.yml
Current key doesn't allow read/write access.
=> Added ssh-key to push.

.pa11yci.json, _layouts/project-page.html
=> Removed side-cta section.
